arrowParens: avoid
bracketSpacing: true
importOrder: ['<THIRD_PARTY_MODULES>', '^[./]']
importOrderParserPlugins: ['typescript']
importOrderSeparation: true
importOrderSortSpecifiers: true
printWidth: 100
semi: false
singleQuote: true
trailingComma: 'es5'

# Solidity official style guid
# https://docs.soliditylang.org/en/v0.8.18/style-guide.html
overrides:
  - files: '*.sol'
    options:
      tabWidth: 4
      singleQuote: false
